version: '3.8'

services:
  tiktok-api:
    build:
      context: .
      dockerfile: Dockerfile.tiktok
    restart: unless-stopped
    container_name: tiktok-downloader-api
    ports:
      - "9000:9000"
    environment:
      - API_URL=http://localhost:9000/
      - API_PORT=9000
      - CORS_WILDCARD=1
      - RATELIMIT_WINDOW=60
      - RATELIMIT_MAX=20
      - DURATION_LIMIT=10800
      # TikTok-specific settings
      - DISABLED_SERVICES=bilibili,bluesky,dailymotion,instagram,facebook,loom,ok,pinterest,reddit,rutube,snapchat,soundcloud,streamable,tumblr,twitch,twitter,vimeo,vk,xiaohongshu,youtube
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
